Update FAQ suite feedback - écran hors tension
TEA-ebook/help-center pull request #138
Opened 2018-02-05 16:29 UTC by LMargot

2018-02-05 16:32 UTC, tut-tuuut commented on _pages/FAQ-liseuse.md
> +La seconde :
Ajoute une ligne vide au-dessus de "la seconde", sinon on ne verra qu'une seule liste. https://github.com/TEA-ebook/help-center/blob/5ee50347b2f16b671103ae97ee7c019658d2deb0/_pages/FAQ-liseuse.md#comment-personnaliser-l%C3%A9cran-hors-tension

2018-02-05 16:33 UTC, tut-tuuut requested changes
OK à part la ligne vide manquante entre les deux listes. :)

2018-02-05 16:35 UTC, tut-tuuut commented on _pages/FAQ-liseuse.md
> +La première :
Tiens, au-dessus de cette ligne aussi il faudrait ajouter une ligne vide, afin de créer un paragraphe séparé et isoler « La première » sur une nouvelle ligne.

2018-02-06 09:30 UTC, astranchet approved these changes

2018-02-06 09:32 UTC, merged