Caractères spéciaux
TEA-ebook/help-center pull request #194
Opened 2019-02-06 09:41 UTC by joannagb

Nouvelle question Comment trouver des caractères spéciaux sur le clavier ?  j'ai choisi de placer cette question dans FAQ_Lecture...  et j'aimerais avoir votre avis si FAQ Liseuse ne serait pas plus approprié +  des remarque sur la formulation /  le contenu Merci

2019-02-06 10:03 UTC, astranchet requested changes
Je mettrais plutôt cette question dans FAQ Liseuse que Lecture (il ne s'agit pas à proprement parler de lecture puisque l'utilisateur veut saisir du texte, soit pour rédiger une note, soit configurer son wifi, son compte...)

Par ailleurs, pour la réponse, je propose : 
```
Il existe deux manières d'afficher les caractères spéciaux sur le clavier de la liseuse : 
* Changer la disposition du clavier avec la touche MAJ (en bas à gauche)
* Changer la langue du clavier pour accéder à d'autres caractères spéciaux, en appuyant sur la touche EN
```

2019-02-06 10:03 UTC, astranchet commented on _pages/FAQ-lecture.md
> +### Comment trouver des caractères spéciaux sur le clavier ?
Je formulerais en "Comment saisir des caractères spéciaux sur le clavier de ma liseuse ?" (pour le contexte, @LMargot, cette question nous est venue en tête suite aux termes de recherche "touche %")

2019-02-06 10:03 UTC, astranchet commented on _pages/FAQ-lecture.md
> +{% include anchor.html id="ebook-incomplet" label="L’ebook est incomplet. Il manque des pages ou des chapitres." %}
L'ancre est incorrecte, elle a encore les paramètres de la question du dessus.

2019-02-06 14:25 UTC, joannagb commented on _pages/FAQ-lecture.md
> +### Comment trouver des caractères spéciaux sur le clavier ?
modifications apportées

2019-02-06 16:02 UTC, astranchet commented on _pages/FAQ-lecture.md
> +### Comment trouver des caractères spéciaux sur le clavier ?
@joannagb : Dans la timeline de cette PR, je ne vois pas d'autres commits (donc d'autres modifications)

2019-02-14 15:52 UTC, astranchet commented
Je ferme cette PR et rajoute cette question dans la FAQ Liseuse plutôt (voir PR #199 )

2019-02-14 15:52 UTC, closed without merging